# Generated by Django 5.2.8 on 2026-07-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('recipe', 'Recipe'), ('chicken', 'Chicken'), ('fish', 'Fish'), ('mutton', 'Mutton'), ('tips', 'Cooking Tips'), ('health', 'Health')], max_length=50)),
                ('featured_image', models.ImageField(upload_to='blogs/')),
                ('excerpt', models.TextField(help_text='Small intro shown on blog page')),
                ('content', models.TextField()),
                ('author', models.CharField(default='Fresh Barrel Team', max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
