# Generated by Django 5.2.8 on 2026-07-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube video link', null=True),
        ),
    ]
