# Generated by Django 5.2.8 on 2026-07-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video_url',
        ),
        migrations.AddField(
            model_name='blog',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
